using System;
using System.Collections.Generic;
using MegaCrit.Sts2.Core.Localization;

namespace Sts2ModInspector.Localization;

/// <summary>
/// Self-contained localization, following the STS2 sister-mod convention: resolve the current
/// language from <see cref="LocManager"/> (3-letter codes eng/kor/jpn/…), look the key up in that
/// language's table, then fall back to English, then to the raw key. Supports {0}-style formatting.
/// The 14 game languages: eng zhs deu esp fra ita jpn kor pol ptb rus spa tha tur.
/// </summary>
public static class Strings
{
    public static string Get(string key, params object[] args)
    {
        var raw = Lookup(key);
        if (args == null || args.Length == 0) return raw;
        try { return string.Format(raw, args); }
        catch { return raw; }
    }

    private static string Lookup(string key)
    {
        var lang = CurrentLanguage();
        if (Tables.TryGetValue(lang, out var table) && table.TryGetValue(key, out var v)) return v;
        if (Tables.TryGetValue("ENG", out var eng) && eng.TryGetValue(key, out var ev)) return ev;
        return key;
    }

    private static string CurrentLanguage()
    {
        try { return (LocManager.Instance?.Language ?? "eng").ToUpperInvariant(); }
        catch { return "ENG"; }
    }

    private static readonly Dictionary<string, Dictionary<string, string>> Tables =
        new(StringComparer.OrdinalIgnoreCase)
    {
        ["ENG"] = new()
        {
            ["badge_conflicts"] = "{0} conflicts",
            ["badge_heavy"] = "{0} heavy",
            ["badge_tooltip"] = "Click for mod diagnostics details.",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "{0} mods · {1} conflicts ({2} critical) · {3} heavy",
            ["env_devconsole_on"] = "Dev console: ON (achievements may be disabled)",
            ["env_devconsole_off"] = "Dev console: off",
            ["env_debug_mods"] = "Debug/cheat mods: {0}",
            ["tab_critical"] = "Critical",
            ["tab_warning"] = "Warning",
            ["tab_heavy"] = "Heavy mods",
            ["sev_high"] = "CRITICAL",
            ["sev_soft"] = "warning",
            ["kind_transpiler"] = "stacked transpilers",
            ["kind_prefix"] = "stacked prefixes (may block the original)",
            ["kind_overlap"] = "shared patch",
            ["conflicts_none_high"] = "No critical conflicts — no method is rewritten or blocked by two mods.",
            ["conflicts_none_soft"] = "No soft conflicts.",
            ["heavy_none"] = "No mods above the weight threshold.",
            ["heavy_init_measured"] = "init {0} ms (measured)",
            ["heavy_init_unmeasured"] = "init not measured (loaded before Mod Inspector)",
            ["heavy_patches"] = "{0} patches",
            ["heavy_note"] = "Init time is only measured for mods loaded after Mod Inspector; earlier mods are estimated by static footprint (pck / dll / patch count).",
            ["note_more"] = "… and {0} more",
            ["btn_save"] = "Save report",
            ["btn_close"] = "Close",
            ["save_ok"] = "Saved: {0}",
            ["save_fail"] = "Save failed (see log)",
        },
        ["KOR"] = new()
        {
            ["badge_conflicts"] = "충돌 {0}",
            ["badge_heavy"] = "무거운 모드 {0}",
            ["badge_tooltip"] = "클릭하면 모드 진단 상세를 봅니다.",
            ["title"] = "🩺 모드 인스펙터",
            ["summary"] = "모드 {0}개 · 충돌 {1}개(심각 {2}) · 무거운 모드 {3}개",
            ["env_devconsole_on"] = "개발자 콘솔: 켜짐 (도전과제 비활성화될 수 있음)",
            ["env_devconsole_off"] = "개발자 콘솔: 꺼짐",
            ["env_debug_mods"] = "디버그/치트 모드: {0}",
            ["tab_critical"] = "심각",
            ["tab_warning"] = "주의",
            ["tab_heavy"] = "무거운 모드",
            ["sev_high"] = "심각",
            ["sev_soft"] = "주의",
            ["kind_transpiler"] = "IL 재작성 중복",
            ["kind_prefix"] = "prefix 중복(원본 차단 위험)",
            ["kind_overlap"] = "동시 패치",
            ["conflicts_none_high"] = "심각 충돌 없음 — 어떤 함수도 두 모드가 재작성/차단하지 않습니다.",
            ["conflicts_none_soft"] = "주의 수준 충돌 없음.",
            ["heavy_none"] = "기준을 넘는 무거운 모드 없음.",
            ["heavy_init_measured"] = "init {0} ms (실측)",
            ["heavy_init_unmeasured"] = "init 미측정(Mod Inspector보다 먼저 로드됨)",
            ["heavy_patches"] = "패치 {0}",
            ["heavy_note"] = "init 시간은 Mod Inspector보다 늦게 로드된 모드만 측정됩니다. 먼저 로드된 모드는 정적 무게(pck/dll/패치 수)로 추정합니다.",
            ["note_more"] = "… 그 외 {0}개 더",
            ["btn_save"] = "리포트 저장",
            ["btn_close"] = "닫기",
            ["save_ok"] = "저장됨: {0}",
            ["save_fail"] = "저장 실패 (로그 확인)",
        },
        ["JPN"] = new()
        {
            ["badge_conflicts"] = "競合 {0}",
            ["badge_heavy"] = "重いMod {0}",
            ["badge_tooltip"] = "クリックでMod診断の詳細を表示します。",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "Mod {0}個 · 競合 {1}件（重大 {2}） · 重いMod {3}個",
            ["env_devconsole_on"] = "開発者コンソール: オン（実績が無効になる場合あり）",
            ["env_devconsole_off"] = "開発者コンソール: オフ",
            ["env_debug_mods"] = "デバッグ/チートMod: {0}",
            ["tab_critical"] = "重大",
            ["tab_warning"] = "注意",
            ["tab_heavy"] = "重いMod",
            ["sev_high"] = "重大",
            ["sev_soft"] = "注意",
            ["kind_transpiler"] = "トランスパイラ重複",
            ["kind_prefix"] = "Prefix重複（元処理を妨げる恐れ）",
            ["kind_overlap"] = "同時パッチ",
            ["conflicts_none_high"] = "重大な競合なし — 2つのModに書き換え／妨害されるメソッドはありません。",
            ["conflicts_none_soft"] = "注意レベルの競合なし。",
            ["heavy_none"] = "しきい値を超える重いModはありません。",
            ["heavy_init_measured"] = "init {0} ms（実測）",
            ["heavy_init_unmeasured"] = "init未計測（Mod Inspectorより先に読み込み）",
            ["heavy_patches"] = "パッチ {0}",
            ["heavy_note"] = "init時間はMod Inspectorより後に読み込まれたModのみ計測します。先に読み込まれたModは静的サイズ（pck/dll/パッチ数）で推定します。",
            ["note_more"] = "… ほか {0} 件",
            ["btn_save"] = "レポート保存",
            ["btn_close"] = "閉じる",
            ["save_ok"] = "保存しました: {0}",
            ["save_fail"] = "保存に失敗（ログ参照）",
        },
        ["ZHS"] = new()
        {
            ["badge_conflicts"] = "冲突 {0}",
            ["badge_heavy"] = "沉重模组 {0}",
            ["badge_tooltip"] = "点击查看模组诊断详情。",
            ["title"] = "🩺 模组检查器",
            ["summary"] = "模组 {0} 个 · 冲突 {1} 个（严重 {2}） · 沉重模组 {3} 个",
            ["env_devconsole_on"] = "开发者控制台：开启（成就可能被禁用）",
            ["env_devconsole_off"] = "开发者控制台：关闭",
            ["env_debug_mods"] = "调试/作弊模组：{0}",
            ["tab_critical"] = "严重",
            ["tab_warning"] = "注意",
            ["tab_heavy"] = "沉重模组",
            ["sev_high"] = "严重",
            ["sev_soft"] = "注意",
            ["kind_transpiler"] = "转译器叠加",
            ["kind_prefix"] = "前缀叠加（可能拦截原方法）",
            ["kind_overlap"] = "共同修补",
            ["conflicts_none_high"] = "无严重冲突 — 没有方法被两个模组改写或拦截。",
            ["conflicts_none_soft"] = "无注意级冲突。",
            ["heavy_none"] = "没有超过阈值的沉重模组。",
            ["heavy_init_measured"] = "init {0} 毫秒（实测）",
            ["heavy_init_unmeasured"] = "init 未测量（早于模组检查器加载）",
            ["heavy_patches"] = "{0} 个补丁",
            ["heavy_note"] = "init 时间仅对晚于模组检查器加载的模组测量；更早加载的模组按静态体积（pck/dll/补丁数）估算。",
            ["note_more"] = "… 还有 {0} 个",
            ["btn_save"] = "保存报告",
            ["btn_close"] = "关闭",
            ["save_ok"] = "已保存：{0}",
            ["save_fail"] = "保存失败（见日志）",
        },
        ["DEU"] = new()
        {
            ["badge_conflicts"] = "{0} Konflikte",
            ["badge_heavy"] = "{0} schwer",
            ["badge_tooltip"] = "Klicken für Mod-Diagnosedetails.",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "{0} Mods · {1} Konflikte ({2} kritisch) · {3} schwer",
            ["env_devconsole_on"] = "Entwicklerkonsole: AN (Erfolge evtl. deaktiviert)",
            ["env_devconsole_off"] = "Entwicklerkonsole: aus",
            ["env_debug_mods"] = "Debug-/Cheat-Mods: {0}",
            ["tab_critical"] = "Kritisch",
            ["tab_warning"] = "Warnung",
            ["tab_heavy"] = "Schwere Mods",
            ["sev_high"] = "KRITISCH",
            ["sev_soft"] = "Warnung",
            ["kind_transpiler"] = "mehrere Transpiler",
            ["kind_prefix"] = "mehrere Prefixe (kann Original blockieren)",
            ["kind_overlap"] = "geteilter Patch",
            ["conflicts_none_high"] = "Keine kritischen Konflikte — keine Methode wird von zwei Mods umgeschrieben oder blockiert.",
            ["conflicts_none_soft"] = "Keine leichten Konflikte.",
            ["heavy_none"] = "Keine Mods über dem Schwellenwert.",
            ["heavy_init_measured"] = "Init {0} ms (gemessen)",
            ["heavy_init_unmeasured"] = "Init nicht gemessen (vor Mod Inspector geladen)",
            ["heavy_patches"] = "{0} Patches",
            ["heavy_note"] = "Die Init-Zeit wird nur für nach Mod Inspector geladene Mods gemessen; früher geladene Mods werden anhand der statischen Größe (pck / dll / Patch-Anzahl) geschätzt.",
            ["note_more"] = "… und {0} weitere",
            ["btn_save"] = "Bericht speichern",
            ["btn_close"] = "Schließen",
            ["save_ok"] = "Gespeichert: {0}",
            ["save_fail"] = "Speichern fehlgeschlagen (siehe Log)",
        },
        ["FRA"] = new()
        {
            ["badge_conflicts"] = "{0} conflits",
            ["badge_heavy"] = "{0} lourds",
            ["badge_tooltip"] = "Cliquez pour les détails du diagnostic des mods.",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "{0} mods · {1} conflits ({2} critiques) · {3} lourds",
            ["env_devconsole_on"] = "Console dev : ACTIVÉE (succès possiblement désactivés)",
            ["env_devconsole_off"] = "Console dev : désactivée",
            ["env_debug_mods"] = "Mods debug/triche : {0}",
            ["tab_critical"] = "Critique",
            ["tab_warning"] = "Avertissement",
            ["tab_heavy"] = "Mods lourds",
            ["sev_high"] = "CRITIQUE",
            ["sev_soft"] = "avertissement",
            ["kind_transpiler"] = "transpileurs cumulés",
            ["kind_prefix"] = "prefixes cumulés (peut bloquer l'original)",
            ["kind_overlap"] = "patch partagé",
            ["conflicts_none_high"] = "Aucun conflit critique — aucune méthode n'est réécrite ou bloquée par deux mods.",
            ["conflicts_none_soft"] = "Aucun conflit léger.",
            ["heavy_none"] = "Aucun mod au-dessus du seuil.",
            ["heavy_init_measured"] = "init {0} ms (mesuré)",
            ["heavy_init_unmeasured"] = "init non mesuré (chargé avant Mod Inspector)",
            ["heavy_patches"] = "{0} patchs",
            ["heavy_note"] = "Le temps d'init n'est mesuré que pour les mods chargés après Mod Inspector ; les mods chargés avant sont estimés par leur taille statique (pck / dll / nombre de patchs).",
            ["note_more"] = "… et {0} de plus",
            ["btn_save"] = "Enregistrer le rapport",
            ["btn_close"] = "Fermer",
            ["save_ok"] = "Enregistré : {0}",
            ["save_fail"] = "Échec de l'enregistrement (voir le journal)",
        },
        ["ITA"] = new()
        {
            ["badge_conflicts"] = "{0} conflitti",
            ["badge_heavy"] = "{0} pesanti",
            ["badge_tooltip"] = "Clicca per i dettagli della diagnostica dei mod.",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "{0} mod · {1} conflitti ({2} critici) · {3} pesanti",
            ["env_devconsole_on"] = "Console sviluppo: ON (obiettivi forse disattivati)",
            ["env_devconsole_off"] = "Console sviluppo: off",
            ["env_debug_mods"] = "Mod debug/cheat: {0}",
            ["tab_critical"] = "Critico",
            ["tab_warning"] = "Avviso",
            ["tab_heavy"] = "Mod pesanti",
            ["sev_high"] = "CRITICO",
            ["sev_soft"] = "avviso",
            ["kind_transpiler"] = "transpiler sovrapposti",
            ["kind_prefix"] = "prefix sovrapposti (può bloccare l'originale)",
            ["kind_overlap"] = "patch condivisa",
            ["conflicts_none_high"] = "Nessun conflitto critico — nessun metodo è riscritto o bloccato da due mod.",
            ["conflicts_none_soft"] = "Nessun conflitto lieve.",
            ["heavy_none"] = "Nessun mod oltre la soglia.",
            ["heavy_init_measured"] = "init {0} ms (misurato)",
            ["heavy_init_unmeasured"] = "init non misurato (caricato prima di Mod Inspector)",
            ["heavy_patches"] = "{0} patch",
            ["heavy_note"] = "Il tempo di init è misurato solo per i mod caricati dopo Mod Inspector; i mod precedenti sono stimati dalla dimensione statica (pck / dll / numero di patch).",
            ["note_more"] = "… e altri {0}",
            ["btn_save"] = "Salva report",
            ["btn_close"] = "Chiudi",
            ["save_ok"] = "Salvato: {0}",
            ["save_fail"] = "Salvataggio non riuscito (vedi log)",
        },
        ["POL"] = new()
        {
            ["badge_conflicts"] = "Konflikty: {0}",
            ["badge_heavy"] = "Ciężkie: {0}",
            ["badge_tooltip"] = "Kliknij, aby zobaczyć szczegóły diagnostyki modów.",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "{0} modów · {1} konfliktów ({2} krytycznych) · {3} ciężkich",
            ["env_devconsole_on"] = "Konsola dev: WŁ. (osiągnięcia mogą być wyłączone)",
            ["env_devconsole_off"] = "Konsola dev: wył.",
            ["env_debug_mods"] = "Mody debug/cheat: {0}",
            ["tab_critical"] = "Krytyczne",
            ["tab_warning"] = "Ostrzeżenie",
            ["tab_heavy"] = "Ciężkie mody",
            ["sev_high"] = "KRYTYCZNE",
            ["sev_soft"] = "ostrzeżenie",
            ["kind_transpiler"] = "nałożone transpilery",
            ["kind_prefix"] = "nałożone prefixy (może blokować oryginał)",
            ["kind_overlap"] = "wspólny patch",
            ["conflicts_none_high"] = "Brak krytycznych konfliktów — żadna metoda nie jest przepisywana ani blokowana przez dwa mody.",
            ["conflicts_none_soft"] = "Brak lekkich konfliktów.",
            ["heavy_none"] = "Brak modów powyżej progu.",
            ["heavy_init_measured"] = "init {0} ms (zmierzone)",
            ["heavy_init_unmeasured"] = "init niezmierzony (załadowany przed Mod Inspector)",
            ["heavy_patches"] = "{0} patchy",
            ["heavy_note"] = "Czas init mierzony jest tylko dla modów załadowanych po Mod Inspector; wcześniejsze są szacowane na podstawie statycznego rozmiaru (pck / dll / liczba patchy).",
            ["note_more"] = "… i {0} więcej",
            ["btn_save"] = "Zapisz raport",
            ["btn_close"] = "Zamknij",
            ["save_ok"] = "Zapisano: {0}",
            ["save_fail"] = "Zapis nieudany (zobacz log)",
        },
        ["PTB"] = new()
        {
            ["badge_conflicts"] = "{0} conflitos",
            ["badge_heavy"] = "{0} pesados",
            ["badge_tooltip"] = "Clique para ver os detalhes do diagnóstico de mods.",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "{0} mods · {1} conflitos ({2} críticos) · {3} pesados",
            ["env_devconsole_on"] = "Console dev: LIGADO (conquistas podem estar desativadas)",
            ["env_devconsole_off"] = "Console dev: desligado",
            ["env_debug_mods"] = "Mods debug/cheat: {0}",
            ["tab_critical"] = "Crítico",
            ["tab_warning"] = "Aviso",
            ["tab_heavy"] = "Mods pesados",
            ["sev_high"] = "CRÍTICO",
            ["sev_soft"] = "aviso",
            ["kind_transpiler"] = "transpilers empilhados",
            ["kind_prefix"] = "prefixes empilhados (pode bloquear o original)",
            ["kind_overlap"] = "patch compartilhado",
            ["conflicts_none_high"] = "Nenhum conflito crítico — nenhum método é reescrito ou bloqueado por dois mods.",
            ["conflicts_none_soft"] = "Nenhum conflito leve.",
            ["heavy_none"] = "Nenhum mod acima do limite.",
            ["heavy_init_measured"] = "init {0} ms (medido)",
            ["heavy_init_unmeasured"] = "init não medido (carregado antes do Mod Inspector)",
            ["heavy_patches"] = "{0} patches",
            ["heavy_note"] = "O tempo de init só é medido para mods carregados após o Mod Inspector; mods anteriores são estimados pelo tamanho estático (pck / dll / nº de patches).",
            ["note_more"] = "… e mais {0}",
            ["btn_save"] = "Salvar relatório",
            ["btn_close"] = "Fechar",
            ["save_ok"] = "Salvo: {0}",
            ["save_fail"] = "Falha ao salvar (veja o log)",
        },
        ["RUS"] = new()
        {
            ["badge_conflicts"] = "Конфликтов: {0}",
            ["badge_heavy"] = "Тяжёлых: {0}",
            ["badge_tooltip"] = "Нажмите для подробностей диагностики модов.",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "Модов: {0} · конфликтов: {1} (критич. {2}) · тяжёлых: {3}",
            ["env_devconsole_on"] = "Консоль разработчика: ВКЛ (достижения могут быть отключены)",
            ["env_devconsole_off"] = "Консоль разработчика: выкл",
            ["env_debug_mods"] = "Debug/чит-моды: {0}",
            ["tab_critical"] = "Критич.",
            ["tab_warning"] = "Внимание",
            ["tab_heavy"] = "Тяжёлые моды",
            ["sev_high"] = "КРИТИЧНО",
            ["sev_soft"] = "внимание",
            ["kind_transpiler"] = "несколько транспайлеров",
            ["kind_prefix"] = "несколько prefix (может блокировать оригинал)",
            ["kind_overlap"] = "общий патч",
            ["conflicts_none_high"] = "Критических конфликтов нет — ни один метод не переписывается и не блокируется двумя модами.",
            ["conflicts_none_soft"] = "Лёгких конфликтов нет.",
            ["heavy_none"] = "Нет модов выше порога.",
            ["heavy_init_measured"] = "init {0} мс (измерено)",
            ["heavy_init_unmeasured"] = "init не измерен (загружен до Mod Inspector)",
            ["heavy_patches"] = "патчей: {0}",
            ["heavy_note"] = "Время init измеряется только для модов, загруженных после Mod Inspector; более ранние оцениваются по статическому размеру (pck / dll / число патчей).",
            ["note_more"] = "… и ещё {0}",
            ["btn_save"] = "Сохранить отчёт",
            ["btn_close"] = "Закрыть",
            ["save_ok"] = "Сохранено: {0}",
            ["save_fail"] = "Не удалось сохранить (см. лог)",
        },
        ["SPA"] = new()
        {
            ["badge_conflicts"] = "{0} conflictos",
            ["badge_heavy"] = "{0} pesados",
            ["badge_tooltip"] = "Haz clic para ver los detalles del diagnóstico de mods.",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "{0} mods · {1} conflictos ({2} críticos) · {3} pesados",
            ["env_devconsole_on"] = "Consola de desarrollo: ON (logros posiblemente desactivados)",
            ["env_devconsole_off"] = "Consola de desarrollo: off",
            ["env_debug_mods"] = "Mods debug/trucos: {0}",
            ["tab_critical"] = "Crítico",
            ["tab_warning"] = "Aviso",
            ["tab_heavy"] = "Mods pesados",
            ["sev_high"] = "CRÍTICO",
            ["sev_soft"] = "aviso",
            ["kind_transpiler"] = "transpiladores apilados",
            ["kind_prefix"] = "prefixes apilados (puede bloquear el original)",
            ["kind_overlap"] = "parche compartido",
            ["conflicts_none_high"] = "Sin conflictos críticos — ningún método es reescrito o bloqueado por dos mods.",
            ["conflicts_none_soft"] = "Sin conflictos leves.",
            ["heavy_none"] = "Ningún mod por encima del umbral.",
            ["heavy_init_measured"] = "init {0} ms (medido)",
            ["heavy_init_unmeasured"] = "init no medido (cargado antes de Mod Inspector)",
            ["heavy_patches"] = "{0} parches",
            ["heavy_note"] = "El tiempo de init solo se mide para los mods cargados después de Mod Inspector; los anteriores se estiman por el tamaño estático (pck / dll / nº de parches).",
            ["note_more"] = "… y {0} más",
            ["btn_save"] = "Guardar informe",
            ["btn_close"] = "Cerrar",
            ["save_ok"] = "Guardado: {0}",
            ["save_fail"] = "Error al guardar (ver registro)",
        },
        ["ESP"] = new()
        {
            ["badge_conflicts"] = "{0} conflictos",
            ["badge_heavy"] = "{0} pesados",
            ["badge_tooltip"] = "Haz clic para ver los detalles del diagnóstico de mods.",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "{0} mods · {1} conflictos ({2} críticos) · {3} pesados",
            ["env_devconsole_on"] = "Consola de desarrollo: ON (logros posiblemente desactivados)",
            ["env_devconsole_off"] = "Consola de desarrollo: off",
            ["env_debug_mods"] = "Mods debug/trucos: {0}",
            ["tab_critical"] = "Crítico",
            ["tab_warning"] = "Aviso",
            ["tab_heavy"] = "Mods pesados",
            ["sev_high"] = "CRÍTICO",
            ["sev_soft"] = "aviso",
            ["kind_transpiler"] = "transpiladores apilados",
            ["kind_prefix"] = "prefixes apilados (puede bloquear el original)",
            ["kind_overlap"] = "parche compartido",
            ["conflicts_none_high"] = "Sin conflictos críticos — ningún método es reescrito o bloqueado por dos mods.",
            ["conflicts_none_soft"] = "Sin conflictos leves.",
            ["heavy_none"] = "Ningún mod por encima del umbral.",
            ["heavy_init_measured"] = "init {0} ms (medido)",
            ["heavy_init_unmeasured"] = "init no medido (cargado antes de Mod Inspector)",
            ["heavy_patches"] = "{0} parches",
            ["heavy_note"] = "El tiempo de init solo se mide para los mods cargados después de Mod Inspector; los anteriores se estiman por el tamaño estático (pck / dll / nº de parches).",
            ["note_more"] = "… y {0} más",
            ["btn_save"] = "Guardar informe",
            ["btn_close"] = "Cerrar",
            ["save_ok"] = "Guardado: {0}",
            ["save_fail"] = "Error al guardar (ver registro)",
        },
        ["THA"] = new()
        {
            ["badge_conflicts"] = "ขัดแย้ง {0}",
            ["badge_heavy"] = "ม็อดหนัก {0}",
            ["badge_tooltip"] = "คลิกเพื่อดูรายละเอียดการวินิจฉัยม็อด",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "ม็อด {0} · ขัดแย้ง {1} (ร้ายแรง {2}) · หนัก {3}",
            ["env_devconsole_on"] = "คอนโซลนักพัฒนา: เปิด (ความสำเร็จอาจถูกปิด)",
            ["env_devconsole_off"] = "คอนโซลนักพัฒนา: ปิด",
            ["env_debug_mods"] = "ม็อดดีบัก/โกง: {0}",
            ["tab_critical"] = "ร้ายแรง",
            ["tab_warning"] = "คำเตือน",
            ["tab_heavy"] = "ม็อดหนัก",
            ["sev_high"] = "ร้ายแรง",
            ["sev_soft"] = "คำเตือน",
            ["kind_transpiler"] = "ทรานสไพเลอร์ซ้อนกัน",
            ["kind_prefix"] = "prefix ซ้อนกัน (อาจบล็อกต้นฉบับ)",
            ["kind_overlap"] = "แพตช์ร่วมกัน",
            ["conflicts_none_high"] = "ไม่มีความขัดแย้งร้ายแรง — ไม่มีเมธอดใดถูกเขียนทับหรือบล็อกโดยสองม็อด",
            ["conflicts_none_soft"] = "ไม่มีความขัดแย้งระดับเบา",
            ["heavy_none"] = "ไม่มีม็อดเกินเกณฑ์",
            ["heavy_init_measured"] = "init {0} ms (วัดได้)",
            ["heavy_init_unmeasured"] = "ไม่ได้วัด init (โหลดก่อน Mod Inspector)",
            ["heavy_patches"] = "{0} แพตช์",
            ["heavy_note"] = "เวลา init วัดเฉพาะม็อดที่โหลดหลัง Mod Inspector; ม็อดที่โหลดก่อนจะประมาณจากขนาดคงที่ (pck / dll / จำนวนแพตช์)",
            ["note_more"] = "… และอีก {0}",
            ["btn_save"] = "บันทึกรายงาน",
            ["btn_close"] = "ปิด",
            ["save_ok"] = "บันทึกแล้ว: {0}",
            ["save_fail"] = "บันทึกไม่สำเร็จ (ดูบันทึก)",
        },
        ["TUR"] = new()
        {
            ["badge_conflicts"] = "{0} çakışma",
            ["badge_heavy"] = "{0} ağır",
            ["badge_tooltip"] = "Mod tanılama ayrıntıları için tıklayın.",
            ["title"] = "🩺 Mod Inspector",
            ["summary"] = "{0} mod · {1} çakışma ({2} kritik) · {3} ağır",
            ["env_devconsole_on"] = "Geliştirici konsolu: AÇIK (başarımlar devre dışı olabilir)",
            ["env_devconsole_off"] = "Geliştirici konsolu: kapalı",
            ["env_debug_mods"] = "Hata ayıklama/hile modları: {0}",
            ["tab_critical"] = "Kritik",
            ["tab_warning"] = "Uyarı",
            ["tab_heavy"] = "Ağır modlar",
            ["sev_high"] = "KRİTİK",
            ["sev_soft"] = "uyarı",
            ["kind_transpiler"] = "üst üste transpiler",
            ["kind_prefix"] = "üst üste prefix (orijinali engelleyebilir)",
            ["kind_overlap"] = "ortak yama",
            ["conflicts_none_high"] = "Kritik çakışma yok — hiçbir metot iki mod tarafından yeniden yazılmıyor veya engellenmiyor.",
            ["conflicts_none_soft"] = "Hafif çakışma yok.",
            ["heavy_none"] = "Eşiğin üzerinde mod yok.",
            ["heavy_init_measured"] = "init {0} ms (ölçüldü)",
            ["heavy_init_unmeasured"] = "init ölçülmedi (Mod Inspector'dan önce yüklendi)",
            ["heavy_patches"] = "{0} yama",
            ["heavy_note"] = "init süresi yalnızca Mod Inspector'dan sonra yüklenen modlar için ölçülür; önce yüklenenler statik boyuta (pck / dll / yama sayısı) göre tahmin edilir.",
            ["note_more"] = "… ve {0} tane daha",
            ["btn_save"] = "Raporu kaydet",
            ["btn_close"] = "Kapat",
            ["save_ok"] = "Kaydedildi: {0}",
            ["save_fail"] = "Kaydetme başarısız (günlüğe bakın)",
        },
    };
}
